### ISSUE TITLE
Searching for the package name doesn’t seem to work anymore

### ISSUE THREAD

**Issue by ausi** [contao/package-list#8]
For example: https://extensions.contao.org/?q=rocksolid-custom-elements

Searching for the exact package name or parts of it doesn’t work anymore, but I think it worked in the past.
Examples I tried:

- `madeyourday/contao-rocksolid-custom-elements`
- `contao-rocksolid-custom-elements`
- `rocksolid-custom-elements`

**Comment by fritzmg** [comment]
It's still working for the `inspiredminds/*` packages for example, but none of the `madeyourday/*` packages. (Searching for `madeyourday/` still works.)

**Comment by aschempp** [comment]
search for `contao-rocksolid` works as well as `custom-elements` 🤔 
I have submitted a support request to Algolia

**Comment by aschempp** [comment]
Since we are on a free/sponsored plan, Algolia support too a bit longer, but they helpfully provided a link to their guide at https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/how-to/how-to-search-in-hyphenated-attributes/

I played around with all the options, and ultimately found that for whatever reason, the `name` attribute was in the list of [camelCaseAttributes](https://www.algolia.com/doc/api-reference/api-parameters/camelCaseAttributes/). Removing that seems to have fixed the issue 🎉

**Comment by ausi** [comment]
Awesome! Thank you very much for investigating and fixing this! ❤️❤️❤️
